//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoadName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoadName()
        {
            this.tblTrafficAccidents = new HashSet<tblTrafficAccident>();
            this.tblTrafficSpeeds = new HashSet<tblTrafficSpeed>();
        }
    
        public int rnID { get; set; }
        public string rnRoadName { get; set; }
        public Nullable<int> rnLocation { get; set; }
        public Nullable<int> rnSpeedLimit { get; set; }
    
        public virtual tblLocationName tblLocationName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrafficAccident> tblTrafficAccidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrafficSpeed> tblTrafficSpeeds { get; set; }
    }
}
