//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRainfall
    {
        public int rfID { get; set; }
        public System.DateTime rfDate { get; set; }
        public int rfLocation { get; set; }
        public decimal rfValue { get; set; }
    
        public virtual tblLocationName tblLocationName { get; set; }
    }
}
