//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrafficAccident
    {
        public int taID { get; set; }
        public System.DateTime taDateTime { get; set; }
        public Nullable<int> taRoadName { get; set; }
        public Nullable<double> taLat { get; set; }
        public Nullable<double> taLong { get; set; }
        public string taDescription { get; set; }
    
        public virtual tblRoadName tblRoadName { get; set; }
    }
}
